hostname: rancher01

rancher:
  network:
    interfaces:
      eth0:
        address: 212.129.50.86/31
        gateway: 62.210.0.1
        dhcp: false
    dns:
      nameservers:
        - 8.8.8.8
        - 1.1.1.1
        - 9.9.9.9
