apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVWGFzaVh0QzlkSzJCZjlNZXZNZ1djNVVhMWRVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSXlNRGN4TmpFMk5EY3pOMW9YRFRNeQpNRGN4TXpFMk5EY3pOMW93RnpFVk1CTUdBMVVFQXd3TU1UQXVNVFV5TGpFNE15NHhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFyV3YvWlhTdWlJWjJPM0pPQTZ2b0RQVklyN3NHU1d5Mk5PZXQKVWlmUThscTJVMnlUa01GQlZkcm0ySWxERTRsamhoUVJ3eWlCTGZnK05Cc1Z5QzZFYWQ2dXlsUEM2d3JHUGw2eApXLzZCZVRqOE9RdmpLT01yTEZJR2ZZTVROdjFMMWU4NVp6WnY1NHV5VzlyK1FHcGdYdm9NaEJ3OUFlektZdkNsCk83RXRpMVlWV21Ka2pZNGtQT0R5UWNRYWNzV2xxL1M0SlR4azBqSld4V2t2N3F5THhuSDFYNmlKQSt0am8yM2IKeFZQbTBCWlpSSXZTMEtpekc1Z1pVUFNLK0t5NlpmYnQ0UDV0TW9nUWk3MVR2RkEvNUJXZ0tjTUNlWlVQVUdSaApkSkdGRno0cVhNVXJsMVo0T0J3Ry93NGRVV09XdjdJZFZWZjZnc05zRVg5QXhobEw2UUlEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVVovcGRwZS9OSDlQNFJacDFEVkJRK210U1RVQXdId1lEVlIwakJCZ3dGb0FVWi9wZHBlL04KSDlQNFJacDFEVkJRK210U1RVQXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBV2dwVU1kOGVkakwwZHAvTmdWQjBMcFhNd3ZNV2J6UmJzeENxRTRlbUNXTVRZMkdtZ0c1ajg5SkNpR24xCjFjaG8vRnhXbHh4aUJmWCtOcnVWQ3dWLzliYjdXaG1VM2dOMWNCMU5rbHMvMTBhWmFNWE9IaW03c3hSczgvbXcKYSsrekpsRlI1S1U1N2xwVGpyN1paZDJwSlBVditFMjJ4V1FyRlNYOUxONTlWMGxhQVlnNGpYNG1Oc29yREJjZQo1UkpsYm9DeXVXWTVRNUQ0UzJ1R21Jdm92UG5oNFF4dDdTSENKYmc2cFdJN2VVME5yamlHN3d3WVo2TDlwejU4CllaaGpkY1FmWTVpa1pXMVA1VXkzeFhTb0h6b2dBbXNVMGJpRFprSzdva3hEOXNyOE1MUFlja2E5M0RwRThJNmcKendUbHNFM25FVW0wV0tMeWVpYkxLUkxMSHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://192.168.200.24:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: cjlwMGVhZkV6WVVOV1oxdzl0VzA0NWVleHZWY2tPMVhLZTNCak5Hc3VCQT0K

