apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: "127.0.0.1:30400/app:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000
